version: "3.8"
services:
  api:
    build:
      args:
        - NODE_ENV=test
      context: ./
    environment:
      - NODE_ENV=test     
    command: bash -c "npm run test:e2e "
    links:
    - redis
    volumes:
    - .:/app/      
  redis:
    container_name: redis
    image: redis:6.2.6
    expose:
      - "6379"
    ports:
      - "6379:6379"
    volumes:
      - ./redisdata:/data
    security_opt:
      - "no-new-privileges:true"